apiVersion: v1
kind: Service
metadata:
  name: lexigrade-ollama
  namespace: lexigrade
spec:
  type: NodePort
  selector:
    app: lexigrade-ollama
  ports:
    - port: 11434
      targetPort: 11434
      nodePort: 31434
