apiVersion: v1
kind: Service
metadata:
  name: lexigrade-api
  namespace: lexigrade
spec:
  type: NodePort
  selector:
    app: lexigrade-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
